name: Reback
version: '${project.version}'
main: me.ninjego.reback.Reback
api-version: 1.19
authors: [ Ninjego ]
description: Replay player movements

commands:
  reback:
    aliases:
      - rb
      - re
    description: Base command for reback plugin